/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    screens: {
      sm: '576px',
      md: '768px',
      lg: '992px',
      xl: '1200px',
      '2xl': '1400px',
    },
    extend: {
      colors: {
        tiko: {
          surface: '#fff8f5',
          'surface-dim': '#f2d4bf',
          'surface-bright': '#fff8f5',
          'surface-container-lowest': '#ffffff',
          'surface-container-low': '#fff1e9',
          'surface-container': '#ffeadc',
          'surface-container-high': '#ffe3cf',
          'surface-container-highest': '#fbddc7',
          'on-surface': '#28180b',
          'on-surface-variant': '#53433d',
          'inverse-surface': '#3f2d1e',
          'inverse-on-surface': '#ffede2',
          outline: '#86736c',
          'outline-variant': '#d8c2ba',
          'surface-tint': '#8e4d31',
          primary: '#8b4b2f',
          'on-primary': '#ffffff',
          'primary-container': '#a86245',
          'on-primary-container': '#fffbff',
          'inverse-primary': '#ffb598',
          secondary: '#665d54',
          'on-secondary': '#ffffff',
          'secondary-container': '#ede0d4',
          'on-secondary-container': '#6c6359',
          tertiary: '#54603f',
          'on-tertiary': '#ffffff',
          'tertiary-container': '#6c7956',
          'on-tertiary-container': '#faffe9',
          error: '#ba1a1a',
          'on-error': '#ffffff',
          'error-container': '#ffdad6',
          'on-error-container': '#93000a',
          'primary-fixed': '#ffdbce',
          'primary-fixed-dim': '#ffb598',
          'on-primary-fixed': '#370e00',
          'on-primary-fixed-variant': '#71361d',
          'secondary-fixed': '#ede0d4',
          'secondary-fixed-dim': '#d1c4b9',
          'on-secondary-fixed': '#211b13',
          'on-secondary-fixed-variant': '#4d453d',
          'tertiary-fixed': '#dae8be',
          'tertiary-fixed-dim': '#becca3',
          'on-tertiary-fixed': '#141f05',
          'on-tertiary-fixed-variant': '#3f4b2c',
          background: '#fff8f5',
          'on-background': '#28180b',
          'surface-variant': '#fbddc7',
        }
      },
      fontFamily: {
        outfit: ['Outfit', 'sans-serif'],
        'dm-sans': ['DM Sans', 'sans-serif'],
        cairo: ['Cairo', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'price-display': ['20px', { lineHeight: '24px', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'arabic-body': ['16px', { lineHeight: '28px', fontWeight: '400' }],
      },
      borderRadius: {
        'tiko-sm': '0.5rem',
        'tiko-default': '1rem',
        'tiko-md': '1.5rem',
        'tiko-lg': '2rem',
        'tiko-xl': '3rem',
      },
      spacing: {
        'tiko-unit': '8px',
        'tiko-container-max': '1280px',
        'tiko-gutter': '24px',
        'tiko-margin-desktop': '64px',
        'tiko-margin-tablet': '32px',
        'tiko-margin-mobile': '20px',
      },
    },
  },
  plugins: [],
}

